In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv(r"C:\Shashank\Banking_Segment\Data\Bank_dataset\bank-additional-full.csv", sep=";")

In [3]:
df.head()

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56,housemaid,married,basic.4y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
1,57,services,married,high.school,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
2,37,services,married,high.school,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
3,40,admin.,married,basic.6y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
4,56,services,married,high.school,no,no,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no

In [4]:
#missing value analysis
(df == "unknown").sum()

unknown_counts = (df == "unknown").sum()
unknown_counts[unknown_counts > 0]

job           330
marital        80
education    1731
default      8597
housing       990
loan          990
dtype: int64

In [5]:
#feature classification
categorical_cols = df.select_dtypes(include='object').columns
numerical_cols = df.select_dtypes(include=['int64','float64']).columns

print("Categorical Features:")
print(categorical_cols)

print("\nNumerical Features:")
print(numerical_cols)

Categorical Features:
Index(['job', 'marital', 'education', 'default', 'housing', 'loan', 'contact',
       'month', 'day_of_week', 'poutcome', 'y'],
      dtype='str')

Numerical Features:
Index(['age', 'duration', 'campaign', 'pdays', 'previous', 'emp.var.rate',
       'cons.price.idx', 'cons.conf.idx', 'euribor3m', 'nr.employed'],
      dtype='str')

C:\Users\shash\AppData\Local\Temp\ipykernel_34072\616931650.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = df.select_dtypes(include='object').columns

In [6]:
#Unique Value Analysis
for col in categorical_cols:
    print(f"\n{col}")
    print(df[col].nunique())

job
12

marital
4

education
8

default
3

housing
3

loan
3

contact
2

month
10

day_of_week
5

poutcome
3

y
2

In [7]:
for col in categorical_cols:
    print(f"\n{col}")
    print(df[col].unique())

job
<StringArray>
[    'housemaid',      'services',        'admin.',   'blue-collar',
    'technician',       'retired',    'management',    'unemployed',
 'self-employed',       'unknown',  'entrepreneur',       'student']
Length: 12, dtype: str

marital
<StringArray>
['married', 'single', 'divorced', 'unknown']
Length: 4, dtype: str

education
<StringArray>
[           'basic.4y',         'high.school',            'basic.6y',
            'basic.9y', 'professional.course',             'unknown',
   'university.degree',          'illiterate']
Length: 8, dtype: str

default
<StringArray>
['no', 'unknown', 'yes']
Length: 3, dtype: str

housing
<StringArray>
['no', 'yes', 'unknown']
Length: 3, dtype: str

loan
<StringArray>
['no', 'yes', 'unknown']
Length: 3, dtype: str

contact
<StringArray>
['telephone', 'cellular']
Length: 2, dtype: str

month
<StringArray>
['may', 'jun', 'jul', 'aug', 'oct', 'nov', 'dec', 'mar', 'apr', 'sep']
Length: 10, dtype: str

day_of_week
<StringArray>
['mon', 'tue', 'wed', 'thu', 'fri']
Length: 5, dtype: str

poutcome
<StringArray>
['nonexistent', 'failure', 'success']
Length: 3, dtype: str

y
<StringArray>
['no', 'yes']
Length: 2, dtype: str

In [8]:
#Removing Target variable (the subscription column)
df_ml = df.drop('y', axis=1)
df_ml.shape

(41188, 20)

In [9]:
categorical_cols = df_ml.select_dtypes(include='object').columns
numerical_cols = df_ml.select_dtypes(include=['int64','float64']).columns

print(categorical_cols)
print("\n")
print(numerical_cols)

Index(['job', 'marital', 'education', 'default', 'housing', 'loan', 'contact',
       'month', 'day_of_week', 'poutcome'],
      dtype='str')


Index(['age', 'duration', 'campaign', 'pdays', 'previous', 'emp.var.rate',
       'cons.price.idx', 'cons.conf.idx', 'euribor3m', 'nr.employed'],
      dtype='str')

C:\Users\shash\AppData\Local\Temp\ipykernel_34072\547511347.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = df_ml.select_dtypes(include='object').columns

In [10]:
#Data Encoding (1-hot encoding)
df_encoded = pd.get_dummies(
    df_ml,
    columns=categorical_cols,
    drop_first=True
)

df_encoded.shape
df_encoded.head()

,age,duration,campaign,pdays,previous,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,...,month_may,month_nov,month_oct,month_sep,day_of_week_mon,day_of_week_thu,day_of_week_tue,day_of_week_wed,poutcome_nonexistent,poutcome_success
0,56,261,1,999,0,1.1,93.994,-36.4,4.857,5191.0,...,True,False,False,False,True,False,False,False,True,False
1,57,149,1,999,0,1.1,93.994,-36.4,4.857,5191.0,...,True,False,False,False,True,False,False,False,True,False
2,37,226,1,999,0,1.1,93.994,-36.4,4.857,5191.0,...,True,False,False,False,True,False,False,False,True,False
3,40,151,1,999,0,1.1,93.994,-36.4,4.857,5191.0,...,True,False,False,False,True,False,False,False,True,False
4,56,307,1,999,0,1.1,93.994,-36.4,4.857,5191.0,...,True,False,False,False,True,False,False,False,True,False

In [11]:
df_encoded.columns

Index(['age', 'duration', 'campaign', 'pdays', 'previous', 'emp.var.rate',
       'cons.price.idx', 'cons.conf.idx', 'euribor3m', 'nr.employed',
       'job_blue-collar', 'job_entrepreneur', 'job_housemaid',
       'job_management', 'job_retired', 'job_self-employed', 'job_services',
       'job_student', 'job_technician', 'job_unemployed', 'job_unknown',
       'marital_married', 'marital_single', 'marital_unknown',
       'education_basic.6y', 'education_basic.9y', 'education_high.school',
       'education_illiterate', 'education_professional.course',
       'education_university.degree', 'education_unknown', 'default_unknown',
       'default_yes', 'housing_unknown', 'housing_yes', 'loan_unknown',
       'loan_yes', 'contact_telephone', 'month_aug', 'month_dec', 'month_jul',
       'month_jun', 'month_mar', 'month_may', 'month_nov', 'month_oct',
       'month_sep', 'day_of_week_mon', 'day_of_week_thu', 'day_of_week_tue',
       'day_of_week_wed', 'poutcome_nonexistent', 'poutcome_success'],
      dtype='str')

In [12]:
print("Original Shape:", df_ml.shape)
print("Encoded Shape:", df_encoded.shape)

Original Shape: (41188, 20)
Encoded Shape: (41188, 53)

In [13]:
df_encoded.select_dtypes(include='object')

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[41188 rows x 0 columns]

In [14]:
df_encoded.to_csv("encoded_dataset.csv", index=False)

In [15]:
#Feature Engineering (age groups)
df_encoded['age_group'] = pd.cut(
    df['age'],
    bins=[0,25,40,60,100],
    labels=[0,1,2,3]
)

df_encoded['age_group'].value_counts()

age_group
1    22102
2    16510
0     1666
3      910
Name: count, dtype: int64

In [32]:
#Age Labeling
age_group_labels = {
    0: "Young",
    1: "Adult",
    2: "Middle_Age",
    3: "Senior"
}

df_encoded['age_group_label'] = (
    df_encoded['age_group']
    .map(age_group_labels)
)

df_encoded['age_group_label'].value_counts()

age_group_label
Adult         22102
Middle_Age    16510
Young          1666
Senior          910
Name: count, dtype: int64

In [16]:
#Feature Engineering (contacted before)

df_encoded['contacted_before'] = (
    df['previous'] > 0
).astype(int)

df_encoded['contacted_before'].value_counts()

contacted_before
0    35563
1     5625
Name: count, dtype: int64

In [34]:
#contacted_before labeling
contact_labels = {
    0: "No",
    1: "Yes"
}

df_encoded['contacted_before_label'] = (
    df_encoded['contacted_before']
    .map(contact_labels)
)

df_encoded['contacted_before_label'].value_counts()

contacted_before_label
No     35563
Yes     5625
Name: count, dtype: int64

In [17]:
median_campaign = df['campaign'].median()

df_encoded['high_campaign'] = (
    df['campaign'] > median_campaign
).astype(int)

df_encoded['high_campaign'].value_counts()

high_campaign
0    28212
1    12976
Name: count, dtype: int64

In [35]:
campaign_labels = {
    0: "Low_Campaign",
    1: "High_Campaign"
}

df_encoded['high_campaign_label'] = (
    df_encoded['high_campaign']
    .map(campaign_labels)
)

df_encoded['high_campaign_label'].value_counts()

high_campaign_label
Low_Campaign     28212
High_Campaign    12976
Name: count, dtype: int64

In [18]:
df_encoded.info()

<class 'pandas.DataFrame'>
RangeIndex: 41188 entries, 0 to 41187
Data columns (total 56 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   age                            41188 non-null  int64
 1   duration                       41188 non-null  int64
 2   campaign                       41188 non-null  int64
 3   pdays                          41188 non-null  int64
 4   previous                       41188 non-null  int64
 5   emp.var.rate                   41188 non-null  float64
 6   cons.price.idx                 41188 non-null  float64
 7   cons.conf.idx                  41188 non-null  float64
 8   euribor3m                      41188 non-null  float64
 9   nr.employed                    41188 non-null  float64
 10  job_blue-collar                41188 non-null  bool
 11  job_entrepreneur               41188 non-null  bool
 12  job_housemaid                  41188 non-null  bool
 13  job_management                 41188 non-null  bool
 14  job_retired                    41188 non-null  bool
 15  job_self-employed              41188 non-null  bool
 16  job_services                   41188 non-null  bool
 17  job_student                    41188 non-null  bool
 18  job_technician                 41188 non-null  bool
 19  job_unemployed                 41188 non-null  bool
 20  job_unknown                    41188 non-null  bool
 21  marital_married                41188 non-null  bool
 22  marital_single                 41188 non-null  bool
 23  marital_unknown                41188 non-null  bool
 24  education_basic.6y             41188 non-null  bool
 25  education_basic.9y             41188 non-null  bool
 26  education_high.school          41188 non-null  bool
 27  education_illiterate           41188 non-null  bool
 28  education_professional.course  41188 non-null  bool
 29  education_university.degree    41188 non-null  bool
 30  education_unknown              41188 non-null  bool
 31  default_unknown                41188 non-null  bool
 32  default_yes                    41188 non-null  bool
 33  housing_unknown                41188 non-null  bool
 34  housing_yes                    41188 non-null  bool
 35  loan_unknown                   41188 non-null  bool
 36  loan_yes                       41188 non-null  bool
 37  contact_telephone              41188 non-null  bool
 38  month_aug                      41188 non-null  bool
 39  month_dec                      41188 non-null  bool
 40  month_jul                      41188 non-null  bool
 41  month_jun                      41188 non-null  bool
 42  month_mar                      41188 non-null  bool
 43  month_may                      41188 non-null  bool
 44  month_nov                      41188 non-null  bool
 45  month_oct                      41188 non-null  bool
 46  month_sep                      41188 non-null  bool
 47  day_of_week_mon                41188 non-null  bool
 48  day_of_week_thu                41188 non-null  bool
 49  day_of_week_tue                41188 non-null  bool
 50  day_of_week_wed                41188 non-null  bool
 51  poutcome_nonexistent           41188 non-null  bool
 52  poutcome_success               41188 non-null  bool
 53  age_group                      41188 non-null  category
 54  contacted_before               41188 non-null  int64
 55  high_campaign                  41188 non-null  int64
dtypes: bool(43), category(1), float64(5), int64(7)
memory usage: 5.5 MB

In [ ]:
#Converting Boolean columns to integers

bool_cols = df_encoded.select_dtypes(include='bool').columns
df_encoded[bool_cols] = df_encoded[bool_cols].astype(int)

df_encoded.info()

<class 'pandas.DataFrame'>
RangeIndex: 41188 entries, 0 to 41187
Data columns (total 56 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   age                            41188 non-null  int64
 1   duration                       41188 non-null  int64
 2   campaign                       41188 non-null  int64
 3   pdays                          41188 non-null  int64
 4   previous                       41188 non-null  int64
 5   emp.var.rate                   41188 non-null  float64
 6   cons.price.idx                 41188 non-null  float64
 7   cons.conf.idx                  41188 non-null  float64
 8   euribor3m                      41188 non-null  float64
 9   nr.employed                    41188 non-null  float64
 10  job_blue-collar                41188 non-null  int64
 11  job_entrepreneur               41188 non-null  int64
 12  job_housemaid                  41188 non-null  int64
 13  job_management                 41188 non-null  int64
 14  job_retired                    41188 non-null  int64
 15  job_self-employed              41188 non-null  int64
 16  job_services                   41188 non-null  int64
 17  job_student                    41188 non-null  int64
 18  job_technician                 41188 non-null  int64
 19  job_unemployed                 41188 non-null  int64
 20  job_unknown                    41188 non-null  int64
 21  marital_married                41188 non-null  int64
 22  marital_single                 41188 non-null  int64
 23  marital_unknown                41188 non-null  int64
 24  education_basic.6y             41188 non-null  int64
 25  education_basic.9y             41188 non-null  int64
 26  education_high.school          41188 non-null  int64
 27  education_illiterate           41188 non-null  int64
 28  education_professional.course  41188 non-null  int64
 29  education_university.degree    41188 non-null  int64
 30  education_unknown              41188 non-null  int64
 31  default_unknown                41188 non-null  int64
 32  default_yes                    41188 non-null  int64
 33  housing_unknown                41188 non-null  int64
 34  housing_yes                    41188 non-null  int64
 35  loan_unknown                   41188 non-null  int64
 36  loan_yes                       41188 non-null  int64
 37  contact_telephone              41188 non-null  int64
 38  month_aug                      41188 non-null  int64
 39  month_dec                      41188 non-null  int64
 40  month_jul                      41188 non-null  int64
 41  month_jun                      41188 non-null  int64
 42  month_mar                      41188 non-null  int64
 43  month_may                      41188 non-null  int64
 44  month_nov                      41188 non-null  int64
 45  month_oct                      41188 non-null  int64
 46  month_sep                      41188 non-null  int64
 47  day_of_week_mon                41188 non-null  int64
 48  day_of_week_thu                41188 non-null  int64
 49  day_of_week_tue                41188 non-null  int64
 50  day_of_week_wed                41188 non-null  int64
 51  poutcome_nonexistent           41188 non-null  int64
 52  poutcome_success               41188 non-null  int64
 53  age_group                      41188 non-null  category
 54  contacted_before               41188 non-null  int64
 55  high_campaign                  41188 non-null  int64
dtypes: category(1), float64(5), int64(50)
memory usage: 17.3 MB

In [20]:
    #Handling Age group
df_encoded['age_group'].dtype

df_encoded['age_group'] = df_encoded['age_group'].astype(int)

labels=[0,1,2,3]

df_encoded['age_group'].dtype

dtype('int64')

In [22]:
#Scaling 
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaled_data = scaler.fit_transform(df_encoded)

In [23]:
scaled_df = pd.DataFrame(
    scaled_data,
    columns=df_encoded.columns
)

In [31]:
print("Final Dataset Shape:", scaled_df.shape)
scaled_df.head()
scaled_df.describe()

Final Dataset Shape: (41188, 56)

,age,duration,campaign,pdays,previous,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,...,month_sep,day_of_week_mon,day_of_week_thu,day_of_week_tue,day_of_week_wed,poutcome_nonexistent,poutcome_success,age_group,contacted_before,high_campaign
count,4.118800e+04,4.118800e+04,4.118800e+04,4.118800e+04,4.118800e+04,4.118800e+04,4.118800e+04,4.118800e+04,4.118800e+04,4.118800e+04,...,41188.000000,4.118800e+04,4.118800e+04,4.118800e+04,4.118800e+04,4.118800e+04,4.118800e+04,4.118800e+04,4.118800e+04,4.118800e+04
mean,-1.490504e-16,-4.830338e-18,-8.832618e-17,-3.533047e-16,4.416309e-17,-4.416309e-17,-3.321064e-14,-8.832618e-17,-4.416309e-16,1.483880e-14,...,0.000000,-4.968348e-17,8.004560e-17,2.760193e-18,1.794126e-17,-1.104077e-16,4.416309e-17,-4.416309e-17,2.208155e-17,-2.208155e-17
std,1.000012e+00,1.000012e+00,1.000012e+00,1.000012e+00,1.000012e+00,1.000012e+00,1.000012e+00,1.000012e+00,1.000012e+00,1.000012e+00,...,1.000012,1.000012e+00,1.000012e+00,1.000012e+00,1.000012e+00,1.000012e+00,1.000012e+00,1.000012e+00,1.000012e+00,1.000012e+00
min,-2.209365e+00,-9.961775e-01,-5.659220e-01,-5.149443e+00,-3.494943e-01,-2.216433e+00,-2.374889e+00,-2.224953e+00,-1.722351e+00,-2.815697e+00,...,-0.118462,-5.104646e-01,-5.145809e-01,-4.943942e-01,-4.960667e-01,-2.514421e+00,-1.857000e-01,-2.321767e+00,-3.977059e-01,-6.781933e-01
25%,-7.699804e-01,-6.027745e-01,-5.659220e-01,1.954139e-01,-3.494943e-01,-1.197935e+00,-8.649547e-01,-4.747909e-01,-1.312994e+00,-9.402810e-01,...,-0.118462,-5.104646e-01,-5.145809e-01,-4.943942e-01,-4.960667e-01,3.977059e-01,-1.857000e-01,-6.687741e-01,-3.977059e-01,-6.781933e-01
50%,-1.942267e-01,-3.019369e-01,-2.049085e-01,1.954139e-01,-3.494943e-01,6.480923e-01,2.994571e-01,-2.803284e-01,7.124599e-01,3.316799e-01,...,-0.118462,-5.104646e-01,-5.145809e-01,-4.943942e-01,-4.960667e-01,3.977059e-01,-1.857000e-01,-6.687741e-01,-3.977059e-01,-6.781933e-01
75%,6.694038e-01,2.341712e-01,1.561049e-01,1.954139e-01,-3.494943e-01,8.390606e-01,7.227225e-01,8.864466e-01,7.724221e-01,8.451701e-01,...,-0.118462,-5.104646e-01,-5.145809e-01,-4.943942e-01,-4.960667e-01,3.977059e-01,-1.857000e-01,9.842184e-01,-3.977059e-01,1.474506e+00
max,5.563310e+00,1.797202e+01,1.928982e+01,1.954139e-01,1.379492e+01,8.390606e-01,2.058168e+00,2.939106e+00,8.208531e-01,8.451701e-01,...,8.441543,1.959000e+00,1.943329e+00,2.022677e+00,2.015858e+00,3.977059e-01,5.385030e+00,2.637211e+00,2.514421e+00,1.474506e+00

In [36]:
#Dataset Summary
summary = pd.DataFrame({
    "Stage": [
        "Original Dataset",
        "After Removing Target Variable",
        "After Encoding & Feature Engineering",
        "Final Scaled Dataset"
    ],
    "Rows": [
        df.shape[0],
        df_ml.shape[0],
        df_encoded.shape[0],
        scaled_df.shape[0]
    ],
    "Columns": [
        df.shape[1],
        df_ml.shape[1],
        df_encoded.shape[1],
        scaled_df.shape[1]
    ]
})

summary

                                  Stage   Rows  Columns
0                      Original Dataset  41188       21
1        After Removing Target Variable  41188       20
2  After Encoding & Feature Engineering  41188       59
3                  Final Scaled Dataset  41188       56

In [37]:
scaled_df.to_csv(
    "processed_bank_dataset.csv",
    index=False
)